{% set version = "0.201" %}

package:
  name: python-leveldb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/leveldb/leveldb-{{ version }}.tar.gz
  sha256: 1cffe776842917e09f073bd6ea5856c64136aebddbe51bd17ea29913472fecbf
  patches:
    - 0001-Use-PyUnicode_DATA.patch

build:
  skip: true  # [win]
  number: 5
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - leveldb 1.18
    - python
    - pip
  run:
    - leveldb 1.18
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - leveldb

about:
  home: http://code.google.com/p/py-leveldb/
  dev_url: https://github.com/rjpower/py-leveldb
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python bindings for leveldb database library

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal
