{% set version = "0.194" %}

package:
  name: python-leveldb
  version: {{ version }}

source:
  fn: leveldb-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/l/leveldb/leveldb-{{ version }}.tar.gz
  sha256: 9c3378b3b4336cc63303e9fe5d054a337d50bafec80ac4628db19a598c0fcd38

build:
  skip: true  # [win]
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - leveldb 1.18
    - python
    - pip
  run:
    - leveldb 1.18
    - python

test:
  imports:
    - leveldb

about:
  home: http://code.google.com/p/py-leveldb/
  license: BSD 3-Clause
  summary: Python bindings for leveldb database library

extra:
  recipe-maintainers:
    - jakirkham
    - sdvillal
