appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WnGAhxyGUaoQQ8TzUMZWK/ESXbz+XkCMP+5x2d6ltLHQDWjdFJaDgI4gtlc5SGWkY+zjGGApoyhWcCY9OfHwVz3SpEDUJa4ambTLLDPmFgDKTttF0/VJ2PwYqyaeFnlc8Tcv+gtUZ/TM9bEnd8vlN08YDoagiKdlkBlYF7c8IrQhNr8vRDKeRo8qkJzCLXgvgnGYK+zhzQZzZubLufZTmkJaY8mwnL3Vm/PqZMpC2F/Uv+8vnOsstXmhDprwob23AT+wvW8SQl8/8KSm3wriRMjaSKzTJw+QypQk0yCBBOvbcS9mAEYI3JVc2fMnGlUDrUY6FhvfsuDop5rt/OKGno9UFZtXRMigDz7UEsBjpUcaBIHkBIbCTZcpwhXUVX9vnmLiglkUDmu49gbiaoBnuvvlhkaLxWK7ALtL89eCoNsJ1npk5VrpOhy38yaF2U1Dc3DrJibm0+AOnbcGCKWgYFK89RbmG2t8lMQJwyfLsilp6loMGn32HRIEgA3VVXb8BNdGtGq706ADbOYsZVdRvOMyZMBa4fH4F8vh1PJPo5zH2YRI6JL9Q52yITJAF4TddhQY1c8XHS0dx988ObTsstRFXuZ8fwuNYiheLsG/HDhdQ2vp1HhIlGlMQDDPXf2gZ2HdSYH5Rs9vqGzIogPdjeibUmIkliqfY25ohujtIeU=}
